<?php

namespace Twispay\Entity;

/**
 * Class ErrorCode
 *
 * @package Twispay\Entity
 * @author Dragos URSU
 * @version GIT: $Id:$
 */
class ErrorCode
{
    const SITE_ID_MISSING = 101;
    const SITE_ID_INVALID = 102;
    const TRANSACTION_MODE_INVALID = 103;
    const CARD_ID_INVALID = 104;
    const EMAIL_INVALID = 105;
    const CUSTOM_DATA_INVALID = 106;
    const SECRET_KEY_MISSING = 107;
    const CUSTOMER_MISSING = 108;
    const ORDER_MISSING = 109;

    const CUSTOMER_ID_MISSING = 201;
    const CUSTOMER_ID_INVALID = 202;
    const FIRST_NAME_INVALID = 203;
    const LAST_NAME_INVALID = 204;
    const COUNTRY_INVALID = 205;
    const STATE_INVALID = 206;
    const CITY_INVALID = 207;
    const ADDRESS_INVALID = 208;
    const ZIP_INVALID = 209;
    const PHONE_INVALID = 210;
    const TAG_INVALID = 211;

    const ORDER_ID_MISSING = 301;
    const ORDER_ID_INVALID = 302;
    const AMOUNT_MISSING = 303;
    const AMOUNT_INVALID = 304;
    const CURRENCY_MISSING = 305;
    const CURRENCY_INVALID = 306;
    const URL_INVALID = 307;
    const ORDER_DESCRIPTION_MISSING = 308;
    const ORDER_DESCRIPTION_INVALID = 309;
    const LEVEL3_DATA_INVALID = 310;
    const INTERVAL_TYPE_MISSING = 311;
    const INTERVAL_TYPE_INVALID = 312;
    const INTERVAL_VALUE_MISSING = 313;
    const INTERVAL_VALUE_INVALID = 314;
    const TRIAL_AMOUNT_INVALID = 315;
    const FIRST_BILL_DATE_MISSING = 316;
    const FIRST_BILL_DATE_INVALID = 317;

    const ITEM_MISSING = 401;
    const ITEM_INVALID = 402;
    const ITEM_UNIT_PRICE_MISSING = 403;
    const ITEM_UNIT_PRICE_INVALID = 404;
    const ITEM_UNITS_MISSING = 405;
    const ITEM_UNITS_INVALID = 406;
    const ITEM_TYPE_MISSING = 407;
    const ITEM_TYPE_INVALID = 408;
    const ITEM_CODE_MISSING = 409;
    const ITEM_CODE_INVALID = 410;
    const ITEM_DESCRIPTION_MISSING = 411;
    const ITEM_DESCRIPTION_INVALID = 412;
    const ITEM_VAT_PERCENT_MISSING = 413;
    const ITEM_VAT_PERCENT_INVALID = 414;

    const AIRLINE_TICKET_NUMBER_MISSING = 501;
    const AIRLINE_TICKET_NUMBER_INVALID = 502;
    const AIRLINE_PASSENGER_NAME_MISSING = 503;
    const AIRLINE_PASSENGER_NAME_INVALID = 504;
    const AIRLINE_FLIGHT_NUMBER_MISSING = 505;
    const AIRLINE_FLIGHT_NUMBER_INVALID = 506;
    const AIRLINE_DEPARTURE_DATE_MISSING = 507;
    const AIRLINE_DEPARTURE_DATE_INVALID = 508;
    const AIRLINE_DEPARTURE_AIRPORT_CODE_MISSING = 509;
    const AIRLINE_DEPARTURE_AIRPORT_CODE_INVALID = 510;
    const AIRLINE_ARRIVAL_AIRPORT_CODE_MISSING = 511;
    const AIRLINE_ARRIVAL_AIRPORT_CODE_INVALID = 512;
    const AIRLINE_CARRIER_CODE_MISSING = 513;
    const AIRLINE_CARRIER_CODE_INVALID = 514;
    const AIRLINE_TRAVEL_AGENCY_CODE_MISSING = 515;
    const AIRLINE_TRAVEL_AGENCY_CODE_INVALID = 516;
    const AIRLINE_TRAVEL_AGENCY_NAME_MISSING = 517;
    const AIRLINE_TRAVEL_AGENCY_NAME_INVALID = 518;

    const RESPONSE_MISSING = 601;
    const RESPONSE_INVALID_DATA = 602;
    const RESPONSE_SSL_INVALID_IV = 603;
    const RESPONSE_NOT_DECRYPTED = 604;
}
